export const ErrorCodes = Object.freeze({
    'ChecklistItemDetail-ChecklistDetail-Association': 'Association error 01',
    'FormElementGroup-Form-Association': 'Association error 02',
    'FormElement-FormElementGroup-Association': 'Association error 03',
    'ConceptAnswer-Concept-Association': 'Association error 04',
    'LocationMapping-AddressLevel-Association': 'Association error 05',
    'Encounter-Individual-Association': 'Association error 06',
    'ProgramEnrolment-Individual-Association': 'Association error 07',
    'IndividualRelationship-Individual-Association': 'Association error 08',
    'GroupSubject-Individual-Association': 'Association error 09',
    'ProgramEncounter-ProgramEnrolment-Association': 'Association error 10',
    'Checklist-ProgramEnrolment-Association': 'Association error 11',
    'ChecklistItem-Checklist-Association': 'Association error 12',
    'VideoTelemetric-Video-Association': 'Association error 13',
    'NoCatchmentFound': 'NoCatchmentFoundErrorMessage',
    'GroupSubjectMapping-MemberSubject-Association' : 'Ignorable Association error 01',
});
