class SchemaNames {
  static Family = "Family";
  static AddressLevel = "AddressLevel";
  static DraftEncounter = "DraftEncounter";
  static EntitySyncStatus = "EntitySyncStatus";
  static Individual = "Individual";
  static ProgramEnrolment = "ProgramEnrolment";
  static ProgramEncounter = "ProgramEncounter";
  static Encounter = "Encounter";
  static ChecklistItem = "ChecklistItem";
  static Extension = "Extension";
  static Identifier = "Identifier";
  static Form = "Form";
  static Format = "EmbeddedFormat";
  static FormElement = "FormElement";
  static FormElementGroup = "FormElementGroup";
  static FormMapping = "FormMapping";
  static KeyValue = "EmbeddedKeyValue";
  static MenuItem = "MenuItem";
  static StringKeyNumericValue = "EmbeddedStringKeyNumericValue";
  static UserSubjectAssignment = "UserSubjectAssignment";
  static DraftSubject = "DraftSubject";
  static SubjectProgramEligibility = "SubjectProgramEligibility";
  static IndividualRelation = "IndividualRelation";
  static IndividualRelationGenderMapping = "IndividualRelationGenderMapping";
  static IndividualRelationship = "IndividualRelationship";
  static IndividualRelationshipType = "IndividualRelationshipType";
  static Task = "Task";
  static TaskStatus = "TaskStatus";
  static TaskType = "TaskType";
  static TaskUnAssignment = "TaskUnAssignment";
  static Video = "Video";
  static VideoTelemetric = "VideoTelemetric";
  static LocationMapping = "LocationMapping";
  static BeneficiaryModePin = "BeneficiaryModePin";
  static Checklist = "Checklist";
  static ChecklistDetail = "ChecklistDetail";
  static ChecklistItemDetail = "ChecklistItemDetail";
  static ChecklistItemStatus = "EmbeddedChecklistItemStatus";
  static Comment = "Comment";
  static Concept = "Concept";
  static EntityApprovalStatus = "EntityApprovalStatus";
  static EmbeddedPoint = "EmbeddedPoint";
}

export default SchemaNames;
